### ISSUE TITLE
Streamline update process

### ISSUE THREAD

**Issue by ivanoblomov** [Spark-Bio/covid-storepoint#10]
# 1. Problem
The current process for updating location data requires a lot of manual massaging, partially [because of known issues](https://github.com/Spark-Bio/covid-storepoint#data-quality-issues), but also because of the lack of a primary key.

# 2. Assumptions
1. The original data set, Evive data, comes to us in [spreadsheet form](https://github.com/Spark-Bio/covid-storepoint/blob/master/data/raw_sources/1204202%20-%20COVID%2019%20Updated.xlsx).
2. The Storepoint map is updated by importing a [transformed version of 1 in csv form](https://github.com/Spark-Bio/covid-storepoint/blob/master/data/store_point.csv) we generate via `rake task update_storepoint`.
3. We recently came across a new data source, CAC, which is accessible via an API.

# 3. Proposed solution
1. Use the CAC data as the source of truth because they maintain a primary key.
2. Create our own independent data store using CAC's primary key.
3. 2 would allow us to merge any updates from Evive or CAC, *while not becoming strictly dependent on API access to CAC*.

**Comment by neilberkman** [comment]
I agree with this proposal!

**Comment by ivanoblomov** [comment]
@neilberkman I'm still working on #8, but I wanted to capture this while it was rattling around in my head. Could you review and point out anything I misunderstood or overlooked?

Especially 3.2. It may be my food coma right now, but I can't see how we could leverage a primary key—and avoid dependence on CAC—without maintaining our own database. It'll add a lot of complexity, but we'd need it for the volunteer's admin interface anyway.

If we don't want the hosting overhead of a db, we'd need write access to CAC—but that would make us totally dependent on them.

**Comment by neilberkman** [comment]
So, yes - I agree with your assessment and had been thinking along similar lines, specifically that we'll need our own datastore for the volunteer's admin interface and more generally I assumed it was inevitable that eventually we'd need our own datastore.

We'll need to figure out the specifics. Should we move to a rails project since we're planning a UI anyway? I'm all for whatever's the most pragmatic solution.

I'd love to hear any thoughts you have on schema, etc. Also happy to discuss live.

**Comment by ivanoblomov** [comment]
I'm all for migrating to Rails; it's the stack I've loved the most over the years!

How about I include ActiveRecord for now since it would expedite #8? We can add the rest of Rails later when we need it.

**Comment by neilberkman** [comment]
> How about I include ActiveRecord for now since it would expedite #8? We can add the rest of Rails later when we need it.

Sounds good, I had also been thinking about doing this incrementally as well.

**Comment by ivanoblomov** [comment]
Effectively closed by #9 and #37.
