### ISSUE TITLE
Gamify code quality

### ISSUE THREAD

**Issue by ivanoblomov** [Spark-Bio/covid-storepoint#15]
There are a variety of SaaS's that can gamify improving code quality with [graphic badges](https://github.com/ivanoblomov/google_maps_geocoder#googlemapsgeocoder) that are automatically updated in the README. Now seems like a good time to integrate them since we're growing the team.

At this point, adding these services would make sense:
- [x] Code Climate grades [maintainability and test coverage](https://codeclimate.com/github/ivanoblomov/google_maps_geocoder).
- [ ]  Inch CI grades [documentation](https://inch-ci.org/github/Ivanoblomov/google_maps_geocoder).

There are others for security and dependencies, but that can wait till we have an app server.

**Comment by ivanoblomov** [comment]
@neilberkman if you want to proceed with the either of the above, we'll need to set up some webhooks, which I think only repo owners have access to.

**Comment by neilberkman** [comment]
@ivanoblomov just made you an admin.

**Comment by neilberkman** [comment]
> @neilberkman if you want to proceed with either of the above, we'll need to set up some webhooks, which I think only repo owners have access to.

I think it's because I'm an organization-level owner. I installed the app for all repos for the organization. Hopefully you can complete the rest of the setup.

**Comment by ivanoblomov** [comment]
Right on, much appreciated!

**Comment by ivanoblomov** [comment]
Code Climate was added in a73f43ab099fca5a429274261d5915a942fb8d39.
