### ISSUE TITLE
Add hours parsing to CACLocation

### ISSUE THREAD

**Issue by ivanoblomov** [Spark-Bio/covid-storepoint#31]
Storepoint expects hours broken down into separate day fields, whereas CAC provides them as a single field.

Let's integrate the existing logic for parsing these hours with `CACLocation`.

**Comment by neilberkman** [comment]
Note that this will be "best effort" - this task does not require getting all of the CAC freeform hour data to parse correctly. For now we just want to run the existing `HourParser` and include the results when the parser is successful.

**Comment by ivanoblomov** [comment]
@neilberkman should we add conditionality for the spreadsheet output? That is, if the hours by day are defined, null out the monolithic `hours` column?
