### ISSUE TITLE
CAC comparison fails due to API change

### ISSUE THREAD

**Issue by neilberkman** [Spark-Bio/covid-storepoint#33]
See issue described here: https://github.com/codersagainstcovidorg/covid19testing-backend/issues/10

Our `compare_cac` task was failing due to the fact that it compares addresses within the same state, and it was relying on `location_address_region` from the CAC data for this.

**Comment by ivanoblomov** [comment]
@neilberkman updated the assignment (since you've got a PR in progress ;).
