### ISSUE TITLE
Integrate ArcGIS data with CAC data

### ISSUE THREAD

**Issue by neilberkman** [Spark-Bio/covid-storepoint#39]
Obtain the full set of data from ArcGis and match records to those we get from the CAC API. The ArcGis data has attributes we'd like to use, e.g. an indication of whether a site is a drive-thru.
​
The [schema is here](https://services.arcgis.com/8ZpVMShClf8U8dae/ArcGIS/rest/services/TestingLocations_public/FeatureServer/0?f=pjson)
​

Sample code for interacting with it:

```ruby
require './lib/geoservices'
service = Geoservice::MapService.new(url: "https://services.arcgis.com/8ZpVMShClf8U8dae/ArcGIS/rest/services/TestingLocations_public/FeatureServer")
data = service.query(0)["features"]
puts "First record:"
pp data.first ; true
puts "Number of records: #{data.size}"
```
​
The `gesoervices` gem hasn't been updated in 4 years. If you run the current 0.10 version you'll get 
​
`OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: tlsv1 alert protocol version)`
​
I hacked my local version:
​
`lib/geservices/base.rb` change line 32 from
​
```ruby
http.ssl_version = :TLSv1
```
​
to:
​
```ruby
http.ssl_version = :TLSv1_2
```

I forked the repo & made the change. https://github.com/Spark-Bio/geoservices-ruby
​
Open question: currently we get exactly 2000 records. I'm not sure if this is a max and if the gem / API supports a cursor.

**Comment by ivanoblomov** [comment]
If there's a default query limit, looks like it's enforced server-side. Here's the complete request including params:
```ruby
irb(main):005:0> data = service.query(0)["features"]
"/8ZpVMShClf8U8dae/ArcGIS/rest/services/TestingLocations_public/FeatureServer/0/query"
{:f=>"json", :where=>"1=1", :outFields=>"*"}
```

**Comment by neilberkman** [comment]
This was overwritten somehow. Reopening (cc @ivanoblomov)
