### ISSUE TITLE
CAC data: parse address components

### ISSUE THREAD

**Issue by neilberkman** [Spark-Bio/covid-storepoint#44]
StorePoint expects street address, city, state and postal code to be parsed out individually. The CAC data just has a single string. The GiSCorps data has a single string with the full address along with state & city parsed out. We could attempt to use this to extract just the street address from the full address but CAC has some data that GiSCorps didn't provide.

CAC actually did provide the individual components but recently changed. See this issue I opened for background: https://github.com/codersagainstcovidorg/covid19testing-backend/issues/10

I think we need to proceed under the assumption that this won't be fixed. It may have been an explicit decision for some reason.

I think we're going to need to run the data through Google's Geocoding API to parse out address components. We could use the `StreetAddress` gem but the Geocoding API is much more sophisticated as it can parse non-standard addresses such as intersections. This is slightly wasteful as we don't need the lat / long since it's provided in the CAC data but it's not that expensive, as long as we  and not 

StorePoint expects just the street address in the address field. In the other export code I was able to piece this together from the results from Google's Geocoding API see Listing.street_address, with a fallback to the StreetAddress address parsing gem.

So, we'll need to do something similar here. Even though we already have lat / long I think it's fine to run this through Google Geocoding. It's relatively inexpensive, as long as we continue to cache results in `geocoder_results.json` as we have been to ensure we don't geocode the same address twice.

This task will involve:
- [x] 1. Refactoring `TestSites::Geocoder`. The `geocode` method currently loops through the locations from `TestSites::Source`. We need to make this flexible so it can accept data from CAC as well.
- [x] 2. Extracting the logic in `TestSites::Listing` that deals with addresses into its own class that we can use with either data source. (**update**: this has been done. The new class is `ComponentizedUSAddress`).
- [x] 3. Modifying `CACLocation` to use the resulting address.

Note: let's continue to the use the lat / long we get from the CAC API rather than whatever we get from Google Geocoding. Most of the data is from GiSCorps and the lat / long may have been manually adjusted, e.g. in a case where the test site is a specific parking lot within a large park or hospital campus, so we should trust their lat / long over whatever Google gives us.

This task will require further analysis but hopefully this is enough direction.

**Comment by ivanoblomov** [comment]
@neilberkman I believe #54 addressed all the above three items, but I haven't been able to confirm the results. Can't get `rake geocode_cac_locations` with the API key set to complete locally, probably due to my unstable net connection.

**Comment by neilberkman** [comment]
👍🏽
